// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzganvncavbtsjpecpjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6Z2Fudm5jYXZidHNqcGVjcGp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3NjQzNDgsImV4cCI6MjA1NTM0MDM0OH0.-dFH_u7EhiVefJlWuPFBNOjoYJnvP6xvxPUjrlIdaOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);